### 로그인
POST http://localhost:3000/user/login
Content-Type: application/json; charset=UTF-8

{
  "userId": "yh",
  "password": "1234"
}
###

### 회원가입
POST http://localhost:3000/user/signup
Content-Type: application/json; charset=UTF-8

{
  "userId": "younghwan",
  "name": "younghwan",
  "password": "1234"
}
###

### 비밀번호 변경
PUT http://localhost:3000/user/update
Content-Type: application/json; charset=UTF-8
Authorization: Bearer

{
  "userId": "younghwan",
  "name": "jeonggi",
  "password": "12341234"
}
###

### 게시물 등록
POST http://localhost:3000/board/articles
Content-Type: application/json; charset=UTF-8

{
  "title": "younghwan",
  "content": "isreally cool",
  "password": 1234,
  "view": 50
}
###

### 게시물 불러오기
GET http://localhost:3000/board/articles
###

### 핫 게시물 내림차순 불러오기
GET http://localhost:3000/board/hot-articles
###

### 게시물 상세보기
GET http://localhost:3000/board/articles/1
###

### 게시물 수정
PUT http://localhost:3000/board/articles/1
Content-Type: application/json; charset=UTF-8

{
  "title": "Younghwa is...",
  "content": "actually adorable",
  "password": 1234
}
###

### 게시물 삭제
DELETE http://localhost:3000/board/articles/1
Content-Type: application/json; charset=UTF-8

{
    "password": 1234
}
###

